let e=!1;function i(){e=window.innerWidth<=640}new Swiper(".swiper-developers",{effect:"slide",centeredSlides:e,slidesPerView:1,spaceBetween:40,loop:!0,createElements:!0,autoplay:!0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},breakpoints:{640:{slidesPerView:2,spaceBetween:40},1024:{slidesPerView:3,spaceBetween:40},1279:{slidesPerView:4,spaceBetween:40}}}),new Swiper(".area-swiper",{effect:"slide",centeredSlides:e,slidesPerView:4,spaceBetween:10,loop:!0,createElements:!0,pagination:!0,autoplay:!0,breakpoints:{370:{slidesPerView:1,spaceBetween:20},640:{slidesPerView:2,spaceBetween:20},1024:{slidesPerView:3,spaceBetween:20},1279:{slidesPerView:4,spaceBetween:20}}}),i(),window.addEventListener("resize",i)
window.addEventListener("load",(()=>{document.querySelector(".quiz-card-btn")?.addEventListener("click",(function(){document.querySelector(".quiz-popup-overly").classList.remove("popup-hidden"),document.body.style.overflow="hidden"})),document.querySelector(".close-icon")?.addEventListener("click",(function(){document.querySelector(".quiz-popup-overly").classList.add("popup-hidden"),document.body.style.overflow="auto"}))})),document.addEventListener("DOMContentLoaded",(function(){const e=new URLSearchParams(window.location.search);e.has("showPopup")&&"true"===e.get("showPopup")&&Marquiz.showModal("664c59806242e700264f71b5")}));
document.querySelectorAll('input[name*="url"]').forEach((e=>{e.value=window.location.href}));
document.addEventListener("DOMContentLoaded",(function(){function t(){document.querySelectorAll(".item_price_aed").forEach((function(t){const e=t.textContent.trim();if(/Call\s*us/i.test(e))return;const n=function(t){if(t=t.replace("AED","").trim(),isNaN(t.replace(/,/g,""))&&!/^\d+(\.\d+)?$/.test(t))return t;let e=/^[0-9]*\.[0-9]+$/.test(t),n=parseFloat(t.replace(/,/g,""));return e?n.toFixed(1)+"M":n>=1e6?(n/1e6).toFixed(1)+"M":n>=1e3?(n/1e3).toFixed(1)+"K":n}(e);t.textContent=n}))}t();new MutationObserver((function(e){e.forEach((function(e){"childList"!==e.type&&"subtree"!==e.type&&"characterData"!==e.type||t()}))})).observe(document.body,{childList:!0,subtree:!0,characterData:!0})}));
document.addEventListener("DOMContentLoaded",(function(){let e=document.querySelector("#download_pdf");console.log(e),e.addEventListener("click",(function(){let e=document.querySelector(".interest_form"),n=document.getElementById("#pdf_Link");e.checkValidity()?(e.submit(),e.addEventListener("submit",(function(e){e.preventDefault();let t=pdfUrlField.href;n?(window.location.href=t,console.log(t,"floor plan link is here")):console.error("PDF URL is not defined.")}),{once:!0})):e.reportValidity()}))}));
!function(e,n,i,t){let o=n.createElement("script");o.async=!0,o.src="//script.marquiz.io/v2.js",o.onload=function(){"loading"!==document.readyState?Marquiz.init(t):document.addEventListener("DOMContentLoaded",(function(){Marquiz.init(t)}))},n.head.insertBefore(o,n.head.firstElementChild)}(window,document,0,{host:"//quiz.marquiz.io",region:"eu",id:"6605da5a5318590026ec45da",autoOpen:15,autoOpenFreq:"once",openOnExit:!1,disableOnMobile:!1});
$(document).ready((function(){$("input[ms-code-phone-number]").each((function(){var t=this,n=$(t).attr("ms-code-phone-number").split(","),e=window.intlTelInput(t,{preferredCountries:n,utilsScript:"https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.js"});function i(){var n=e.getNumber(intlTelInputUtils.numberFormat.NATIONAL);t.value=n}$.get("https://ipinfo.io",(function(t){var n=t.country;e.setCountry(n)}),"jsonp"),t.addEventListener("change",i),t.addEventListener("keyup",i),$(t).closest("form").submit((function(){var n=e.getNumber(intlTelInputUtils.numberFormat.INTERNATIONAL);t.value=n}))}))}));
document.addEventListener("DOMContentLoaded",(function(){let e=document.querySelector(".floorplan-section"),n=document.querySelector(".floor_plans_list");e.style.display=null===n?"none":"block"}));
let e=document.querySelector(".developer-select"),t=document.querySelector(".developer-filter");e?.addEventListener("change",(function(){t.value=e.value,console.log(t.value);const n=new Event("input",{bubbles:!0,cancelable:!0});t.dispatchEvent(n)}));let n=document.querySelector(".custom-are-select"),c=document.querySelector(".custom-area-search");n?.addEventListener("change",(function(){c.value=n.value,console.log(c.value);const e=new Event("input",{bubbles:!0,cancelable:!0});c.dispatchEvent(e)}));
document.addEventListener("DOMContentLoaded",(function(){let e=document.querySelector(".amenities_texts"),t=e.textContent.split(","),n=document.createElement("ul");n.classList.add("amenities__wrapper"),t.forEach((function(e){let t=document.createElement("li");t.textContent=e,n.appendChild(t)})),e.parentNode.replaceChild(n,e)}));
